#!/bin/sh -ex

. inc/common
mkdir -p /srv/www/htdocs
rm -f /etc/apache2/sites-available/*
rm -f /etc/apache2/sites-enabled/*

a2enmod actions rewrite alias headers php5

juju-log "Installing Apache  config..."
install -o root -g root -m 0644 files/charm/apache/etc_apache2_sites-enabled_livestreet /etc/apache2/sites-available/livestreet.conf

install -o root -g root -m 0644 files/charm/apache/etc_apache2_ports /etc/apache2/ports.conf


juju-log "Installing nginx config..."
install -o root -g root -m 0644 files/charm/nginx/etc_nginx_sites-enabled_livestreet /etc/nginx/sites-available/livestreet.conf
ln -s /etc/nginx/sites-available/livestreet.conf /etc/nginx/sites-enabled/livestreet.conf


a2ensite livestreet

juju-log "Installing sphinx config..."
install -o root -g root -m 0644 files/charm/sphinx/etc_sphinx_sphinx-conf /etc/sphinxsearch/sphinx.conf

juju-log "first index"
/usr/bin/indexer --rotate entityprefixtopicsIndex
/usr/bin/indexer --rotate entityprefixcommentsIndex

service sphinxsearch start
service apache2 restart
service nginx restart


juju-log "Restarting Services ..."
hooks/restart
